# Collector specific configuration
commit_limit: 1000

HAPI_countries:
  - AFG
  - BFA
  - CAF
  - CMR
  - COD
  - COL
  - ETH
  - GTM
  - HND
  - HTI
  - MLI
  - MMR
  - MOZ
  - NER
  - NGA
  - PSE
  - SDN
  - SLV
  - SOM
  - SSD
  - SYR
  - TCD
  - UKR
  - VEN
  - YEM

country_name_overrides:
  BOL: "Bolivia"
  VEN: "Venezuela"

country_name_mappings:
  "Congo DR": "COD"

admin1:
  admin_name_mappings:
    "ETH|B. Gumuz": "ET06"
    "NGA|Abuja": "NG015"
    "SDN|Eastern Darfur": "SD05"
    "SDN|Nile": "SD16"
    "SOM|Juba Dhexe": "SO27"
    "SOM|Juba Hoose": "SO28"
    "SOM|Shabelle Dhexe": "SO21"
    "SOM|Shabelle Hoose": "SO23"
    "TCD|Mayo Kebbi Ouest": "TD12"
    "UKR|Avtonomna Respublika Krym": "UA01"
    "UKR|Kyivska": "UA80"
    "YEM|Amanat Al Asimah": "YE13"

admin2:
  admin_name_mappings:
    "AF08|Onaba": "AF0805"
    "AF14|Khost": "AF1401"
    "AF23|Chaghcharan": "AF2301"
    "CO08|Distrito Especial, Industrial Y Portuario De Barranquilla": "CO08001"
    "ET01|C. TIGRAY": "ET0102"
    "ET01|NW. TIGRAY": "ET0101"
    "ET02|ZONE1": "ET0201"
    "ET02|ZONE3": "ET0203"
    "ET02|ZONE4": "ET0204"
    "ET02|ZONE5": "ET0205"
    "ET05|DEGEHABUR": "ET0503"
    "ET05|FIK": "ET0504"
    "ET05|GODE": "ET0506"
    "ET05|JIJIGA": "ET0502"
    "ET05|SHINILE": "ET0501"
    "ET05|WARDER": "ET0507"
    "ET07|SIDAMA": "ET1600"
    "ET12|GODERE": "ET1203"
    "ET12|ZONE 1": "ET1204"
    "ET12|ZONE 2": "ET1202"
    "ET12|ZONE 3": "ET1201"
    "ET13|HARAR/HUNDENE": "ET1301"
    "ET14|AA ZONE1": "ET1401"
    "GT13|San Idelfonso Ixtahuac√°n": "GT1309"
    "ML07|Menaka": "ML1001"
    "NE006|Tagazar": "NE006003"
    "PS01|Ramallah and Albireh": "PS0130"
    "SD01|Sharq El Nile": "SD01004"
    "SD10|Al Gonnob & Al Oleb": "SD10069"
    "SD11|Wad Al Helew": "SD11061"
    "SD12|Al Galabat Eastern": "SD12083"
    "SD12|Al Gedaref Rural": "SD12080"
    "SD15|Wad Madani El Kobra": "SD15030"
    "SD18|El Salam": "SD18086"
    "TD17|Iriba": "TD1703"
    "UA12|Apostolivskyi": "UA1206"
    "UA12|Marhanetska": "UA1208"
    "UA12|Ordzhonikidzevska": "UA1208"
    "UA12|Pokrovskyi": "UA1214"
    "UA12|Sofiivskyi": "UA1206"
    "UA12|Tomakivskyi": "UA1208"
    "UA14|Amvrosiivskyi": "UA1408"
    "UA14|Avdiivska": "UA1416"
    "UA14|Debaltsevcka": "UA1406"
    "UA14|Dobropilska": "UA1416"
    "UA14|Dobropilskyi": "UA1416"
    "UA14|Dokuchaievska": "UA1410"
    "UA14|Dymytrivska": "UA1416"
    "UA14|Khartsyzka": "UA1408"
    "UA14|Kirovska": "UA1406"
    "UA14|Kostiantynivska": "UA1412"
    "UA14|Kostiantynivskyi": "UA1412"
    "UA14|Lymanska": "UA1412"
    "UA14|Marinskyi": "UA1416"
    "UA14|Novoazovskyi": "UA1410"
    "UA14|Novohrodivska": "UA1416"
    "UA14|Selydivska": "UA1416"
    "UA14|Shakhtarskyi": "UA1406"
    "UA14|Slovianska": "UA1412"
    "UA14|Snizhnianska": "UA1406"
    "UA14|Toretska": "UA1402"
    "UA14|Torezka": "UA1406"
    "UA14|Velykonovosilkivskyi": "UA1404"
    "UA14|Vuhledarska": "UA1404"
    "UA14|Yasynuvatska": "UA1408"
    "UA14|Yasynuvatskyi": "UA1416"
    "UA14|Yenakiivska": "UA1406"
    "UA63|Balakliiskyi": "UA6304"
    "UA63|Blyzniukivskyi": "UA6310"
    "UA63|Borivskyi": "UA6304"
    "UA63|Derhachivskyi": "UA6312"
    "UA63|Dvorichanskyi": "UA6308"
    "UA63|Liubotynska": "UA6312"
    "UA63|Novovodolazkyi": "UA6312"
    "UA63|Pervomaiska": "UA6310"
    "UA63|Shevchenkivskyi": "UA6308"
    "UA63|Velykoburlutskyi": "UA6308"
    "UA63|Vovchanskyi": "UA6314"
    "UA63|Zolochivskyi": "UA6302"
    "UA65|Bilozerskyi": "UA6510"
    "UA65|Chaplynskyi": "UA6506"
    "UA65|Holoprystanska": "UA6508"
    "UA65|Hornostaivskyi": "UA6506"
    "UA65|Kalanchatskyi": "UA6508"
    "UA65|Novokakhovska": "UA6506"
    "UA65|Novovorontsovskyi": "UA6502"
    "UA65|Oleshkivskyi": "UA6510"
    "UA65|Velykolepetyskyi": "UA6506"
    "UA65|Velykooleksandrivskyi": "UA6502"
    "UA65|Verkhnorohachytskyi": "UA6506"
    "UA65|Vysokopilskyi": "UA6502"
    "UA35|Kirovohradska": "UA3504"
    "UA35|Malovyskivskyi": "UA3506"
    "UA44|Troitskyi": "UA4410"
    "UA48|Arbuzynskyi": "UA4808"
    "UA48|Berezanskyi": "UA4806"
    "UA48|Bereznehuvatskyi": "UA4802"
    "UA48|Kazankivskyi": "UA4802"
    "UA48|Novobuzkyi": "UA4802"
    "UA48|Novoodeskyi": "UA4806"
    "UA48|Ochakivska": "UA4806"
    "UA48|Snihurivskyi": "UA4802"
    "UA48|Veselynivskyi": "UA4804"
    "UA48|Vitovskyi": "UA4806"
    "UA48|Vradiivskyi": "UA4808"
    "UA48|Yelanetskyi": "UA4804"
    "UA48|Yuzhnoukrainska": "UA4804"
    "UA59|Bilopilskyi": "UA5908"
    "UA59|Burynskyi": "UA5902"
    "UA59|Hlukhivska": "UA5910"
    "UA59|Hlukhivskyi": "UA5910"
    "UA59|Krasnopilskyi": "UA5908"
    "UA59|Krolevetskyi": "UA5902"
    "UA59|Lebedynska": "UA5908"
    "UA59|Lypovodolynskyi": "UA5906"
    "UA59|Nedryhailivskyi": "UA5906"
    "UA59|Putyvlskyi": "UA5902"
    "UA59|Seredyno-Budskyi": "UA5910"
    "UA59|Trostianetskyi": "UA5904"
    "UA59|Velykopysarivskyi": "UA5904"
    "UA59|Yampilskyi": "UA5910"
    "UA23|Bilmatskyi": "UA2310"
    "UA23|Chernihivskyi": "UA2302"
    "UA23|Enerhodarska": "UA2304"
    "UA23|Huliaipilskyi": "UA2310"
    "UA23|Kamiansko-Dniprovskyi": "UA2304"
    "UA23|Novomykolaivskyi": "UA2306"
    "UA23|Pryazovskyi": "UA2308"
    "UA23|Prymorskyi": "UA2302"
    "UA23|Rozivskyi": "UA2310"
    "UA23|Tokmatska": "UA2310"
    "UA23|Tokmatskyi": "UA2310"
    "UA23|Vilnianskyi": "UA2306"
    "UA23|Yakymivskyi": "UA2308"
    "YE14|Radman Al Awad": "YE1412"
    "YE24|Craiter": "YE2407"
    "YE26|Medghal": "YE2603"

  admin_name_replacements:
    "COD| city": ""
    "ETH|c.": "central"
    "ETH|e.": "east"
    "ETH|n.": "north"
    "ETH|s.": "south"
    "ETH|w.": "west"

orphan_admin2s:
  SS0001: "SSD"

sector:
  dataset: "global-coordination-groups-beta"
  resource: "Global Coordination Groups (Beta) CSV"
  format: "csv"
  headers: 2

org:
  url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSfBWvSu3fKA743VvHtgf-pIGkYH7zhy-NP7DZgEV9_a6YU7vtCeWhbLM56aUL1iIfrfv5UBvvjVt7B/pub?gid=1040329566&single=true&output=csv"

org_type:
  dataset: "organization-types-beta"
  resource: "Organization Types (Beta) - CSV"
  format: "csv"
  headers: 2

org_type_map:
  academy: "431"
  agence un: "447"
  agence du systeme des nations unies: "447"
  autre type: "443"
  civile society: "501"
  cooperation internationale: "501"
  croix rouge: "445"
  donantes: "433"
  entite gouvernementale: "435"
  gouvernement: "435"
  gov: "435"
  govt: "435"
  ingo: "437"
  institution etatique: "435"
  international institution: "438"
  local ngo: "504"
  mouv cr: "445"
  mouvement croix rouge: "445"
  mouvement de la croix rouge: "445"
  movimiento de la cruz roja media luna roja: "445"
  nations unies: "447"
  naciones unidas: "447"
  nngo: "441"
  observer: "502"
  ong int: "437"
  ong internacional: "437"
  ong internationale: "437"
  ong nat: "441"
  ong national: "441"
  ong nacional: "441"
  ong nationale: "441"
  organisation des nations unies: "447"
  organismo internacional: "438"
  otro: "443"
  programme de developpement: "503"
  red cross: "445"
  red cross movement: "445"
  red cross mvt: "445"
  red cross and red crescent movement: "445"
  religious group: "446"
  service etatique: "435"
  sociedad civil: "501"
  societe civile: "501"
  un: "447"
  un agency: "447"
  un agencies: "447"

sector_map:
  abna: "SHL"
  abri: "SHL"
  abri bna: "SHL"
  abris: "SHL"
  abris ame: "SHL"
  abris/bna: "SHL"
  abris/bna/cccm: "SHL"
  abris / nfi: "SHL"
  abris d'urgence et nfi: "SHL"
  action contre les mines: "PRO-MIN"
  aee: "SHL"
  agriculture: "FSC"
  agua saneamiento e higiene: "WSH"
  all: "Intersectoral"
  ame: "SHL"
  alojamiento de emergencia: "SHL"
  alojamiento de emergencia (shelter): "SHL"
  alojamientos y asentamientos: "SHL"
  ash: "WSH"
  assainissement: "WSH"
  camp coordination camp management: "CCM"
  camp coordination and camp management: "CCM"
  cash: "Cash"
  cccm: "CCM"
  ccs: "CCM"
  cluster coordination: "CCM"
  coord & services support: "CCM"
  coordination: "CCM"
  coordinacion / informacion: "CCM"
  coordination et gestion des camps: "CCM"
  eah: "WSH"
  eau: "WSH"
  eau assainissement et hygiene: "WSH"
  eau hygiene: "WSH"
  eau hygiene assainissement: "WSH"
  eau hygiene et assainissement: "WSH"
  educacion: "EDU"
  education: "EDU"
  educacion en emergencias: "EDU"
  eha: "WSH"
  emergency shelter and non food items: "SHL"
  epah: "WSH"
  erl: "ERY"
  esnfi: "SHL"
  food: "FSC"
  food security and agriculture: "FSC"
  food security and livelihoods: "FSC"
  food security and nutrition: "FSC"
  food security livelihood: "FSC"
  fsl: "FSC"
  gbv: "PRO-GBV"
  humanitaire: "Hum"
  hygiene: "WSH"
  hygiene assainissement: "WSH"
  logement terre et biens: "PRO-HLP"
  logistica: "LOG"
  logistique: "LOG"
  manejo y gestion de campamentos: "CCM"
  ms: "Multi"
  multi secteur: "Multi"
  multisectoriel: "Multi"
  nutricion: "NUT"
  nutrition: "NUT"
  operatioanl presence water sanitation & hygiene: "WSH"
  operational presence education in emergencies: "EDU"
  operational presence emergency shelter & non food items: "SHL"
  operational presence food security & agriculture: "FSC"
  operational presence health: "HEA"
  operational presence nutrition: "NUT"
  operational presence protection: "PRO"
  pronna: "PRO-CPN"
  propg: "PRO"
  proteccion infantil: "PRO-CPN"
  protection: "PRO"
  protection de l'enfance: "PRO-CPN"
  protection de l'enfant: "PRO-CPN"
  protection generale: "PRO"
  protection logement terre et propriete: "PRO-HLP"
  protection lutte anti mines: "PRO-MIN"
  protection protection de l'enfant: "PRO-CPN"
  protection violences basees sur le genre: "PRO-GBV"
  proteccion: "PRO"
  provbg: "PRO-GBV"
  psea: "PRO-GBV"
  rapid response mechanism: "ERY"
  rcf: "CCM"
  rcf education: "EDU"
  rcf food security and livelihoods: "FSC"
  rcf health and nutrtion: "HEA"
  rcf protection: "PRO"
  recuperacion temprana: "ERY"
  relevement rapide: "ERY"
  relevement precoce: "ERY"
  refugee response: "CCM"
  refugees & migrants multi sector: "CCM"
  reponse aux refugies: "CCM"
  sa: "FSC"
  sal: "HEA"
  salud: "HEA"
  samv: "FSC"
  sante: "HEA"
  securite alimentaire: "FSC"
  seguridad alimentaria: "FSC"
  seguridad alimentaria y nutricion: "FSC"
  services humanitaires communs: "Hum"
  sexual and reproductive health: "HEA"
  shelter: "SHL"
  shelter nfis: "SHL"
  shelter/nfi: "SHL"
  shelter and nfi: "SHL"
  shelter and nfis: "SHL"
  shelter and non food items: "SHL"
  site management: "CCM"
  snfi: "SHL"
  telecommunications: "TEL"
  telecomunicaciones de emergencia: "TEL"
  telecommunications d'urgence: "TEL"
  vbg: "PRO-GBV"
  violences basees sur le genre: "PRO-GBV"
  violencia basada en genero: "PRO-GBV"
  wash: "WSH"
  water sanitation and hygiene: "WSH"
